# Generated by Django 4.1.4 on 2022-12-11 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="New Schema", max_length=255, null=True
                    ),
                ),
                (
                    "column_separator",
                    models.CharField(
                        choices=[
                            (",", "Comma(,)"),
                            (";", "Semilicon(;)"),
                            ("\t", "Tab(\t)"),
                            (" ", "Space( )"),
                            ("|", "Pipe(|)"),
                        ],
                        default=",",
                        max_length=1,
                    ),
                ),
                (
                    "string_character",
                    models.CharField(
                        choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')")],
                        default='"',
                        max_length=1,
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
